site_name: Experimenting with MkDocs

pages:
- Home: 'index.md'
- About: 'about.md'
- How-To: 
    - 'Running Your WebView off the UI Thread': 'How-To/webview.md'
    - 'Limitations of Off-UI Thread Webviews': 'How-To/limitations.md'

theme: flatly